# Generated by Django 3.1.1 on 2020-09-25 01:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book_description',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_name', models.CharField(max_length=200)),
                ('synopsis', models.TextField()),
                ('author', models.CharField(max_length=200)),
                ('volume', models.IntegerField()),
                ('version', models.IntegerField()),
                ('category', models.CharField(max_length=200)),
                ('date_insert_book', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
    ]
