# Generated by Django 3.1.1 on 2020-10-07 02:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('APLICATION_LIBRARY_PRECISA', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book_description',
            name='url_image',
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
